# Generated by Django 5.1.15 on 2026-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_case_compensation_amount_eur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="airline_motive_details",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="airline_motive_known",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="cancellation_notice_timing",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="delay_arrival_timing",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="denied_boarding_reason",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="denied_boarding_voluntary",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="disruption_type",
            field=models.CharField(blank=True, choices=[("CANCELLATION", "Cancellation"), ("DELAY", "Delay"), ("DENIED_BOARDING", "Denied Boarding")], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="incident_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]