# Generated by Django 5.1.15 on 2026-07-24 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_case_airline_motive_details_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="colleague",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_cases", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="Disruption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("disruption_type", models.CharField(choices=[("CANCELLATION", "Cancellation"), ("DELAY", "Delay"), ("DENIED_BOARDING", "Denied Boarding")], max_length=32)),
                ("cancellation_notice_timing", models.CharField(blank=True, max_length=32, null=True)),
                ("delay_arrival_timing", models.CharField(blank=True, max_length=32, null=True)),
                ("denied_boarding_voluntary", models.CharField(blank=True, max_length=16, null=True)),
                ("denied_boarding_reason", models.CharField(blank=True, max_length=64, null=True)),
                ("airline_motive_known", models.CharField(blank=True, max_length=16, null=True)),
                ("airline_motive_details", models.CharField(blank=True, max_length=64, null=True)),
                ("incident_description", models.TextField()),
                ("case", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="disruption", to="cases.case")),
            ],
        ),
    ]