from django.db import models


COMPENSATION_THRESHOLD_SHORT_HAUL_KM = 1500
COMPENSATION_THRESHOLD_MEDIUM_HAUL_KM = 3500
COMPENSATION_AMOUNT_SHORT_HAUL_EUR = 250
COMPENSATION_AMOUNT_MEDIUM_HAUL_EUR = 400
COMPENSATION_AMOUNT_LONG_HAUL_EUR = 600


class CaseStatus(models.TextChoices):
    NEW = "NEW", "New"
    VALID = "VALID", "Valid"
    ASSIGNED = "ASSIGNED", "Assigned"
    INVALID = "INVALID", "Invalid"


class DocumentType(models.TextChoices):
    BOARDING_PASS = "BOARDING_PASS", "Boarding Pass"
    ID_OR_PASSPORT = "ID_OR_PASSPORT", "ID or Passport"


ALLOWED_DOCUMENT_EXTENSIONS = {".pdf", ".jpg", ".jpeg"}
MAX_DOCUMENT_SIZE_BYTES = 5 * 1024 * 1024
MAX_CONNECTING_FLIGHTS = 4
MAX_TOTAL_FLIGHTS = 5
